project:
  type: website
  output-dir: docs

website:
  title: "Demo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de

format:
  html:
    theme: 
      cosmo
    lang: es
    css: styles.css
    toc: true
    code-block-border-left: "darkorange"
    code-block-bg: true
    fig-align: left



